/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.churchmutual.core.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CMICAccountEntry service. Represents a row in the &quot;cmic_CMICAccountEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.churchmutual.core.model.impl.CMICAccountEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.churchmutual.core.model.impl.CMICAccountEntryImpl</code>.
 * </p>
 *
 * @author Kayleen Lim
 * @see CMICAccountEntry
 * @generated
 */
@ProviderType
public interface CMICAccountEntryModel extends BaseModel<CMICAccountEntry> {

	/**
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cmic account entry model instance should use the {@link CMICAccountEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this cmic account entry.
	 *
	 * @return the primary key of this cmic account entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cmic account entry.
	 *
	 * @param primaryKey the primary key of this cmic account entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the cmic account entry ID of this cmic account entry.
	 *
	 * @return the cmic account entry ID of this cmic account entry
	 */
	public long getCmicAccountEntryId();

	/**
	 * Sets the cmic account entry ID of this cmic account entry.
	 *
	 * @param cmicAccountEntryId the cmic account entry ID of this cmic account entry
	 */
	public void setCmicAccountEntryId(long cmicAccountEntryId);

	/**
	 * Returns the account entry ID of this cmic account entry.
	 *
	 * @return the account entry ID of this cmic account entry
	 */
	public long getAccountEntryId();

	/**
	 * Sets the account entry ID of this cmic account entry.
	 *
	 * @param accountEntryId the account entry ID of this cmic account entry
	 */
	public void setAccountEntryId(long accountEntryId);

	/**
	 * Returns the account number of this cmic account entry.
	 *
	 * @return the account number of this cmic account entry
	 */
	@AutoEscape
	public String getAccountNumber();

	/**
	 * Sets the account number of this cmic account entry.
	 *
	 * @param accountNumber the account number of this cmic account entry
	 */
	public void setAccountNumber(String accountNumber);

	/**
	 * Returns the num expired policies of this cmic account entry.
	 *
	 * @return the num expired policies of this cmic account entry
	 */
	public int getNumExpiredPolicies();

	/**
	 * Sets the num expired policies of this cmic account entry.
	 *
	 * @param numExpiredPolicies the num expired policies of this cmic account entry
	 */
	public void setNumExpiredPolicies(int numExpiredPolicies);

	/**
	 * Returns the num future policies of this cmic account entry.
	 *
	 * @return the num future policies of this cmic account entry
	 */
	public int getNumFuturePolicies();

	/**
	 * Sets the num future policies of this cmic account entry.
	 *
	 * @param numFuturePolicies the num future policies of this cmic account entry
	 */
	public void setNumFuturePolicies(int numFuturePolicies);

	/**
	 * Returns the num in force policies of this cmic account entry.
	 *
	 * @return the num in force policies of this cmic account entry
	 */
	public int getNumInForcePolicies();

	/**
	 * Sets the num in force policies of this cmic account entry.
	 *
	 * @param numInForcePolicies the num in force policies of this cmic account entry
	 */
	public void setNumInForcePolicies(int numInForcePolicies);

	/**
	 * Returns the total billed premium of this cmic account entry.
	 *
	 * @return the total billed premium of this cmic account entry
	 */
	@AutoEscape
	public String getTotalBilledPremium();

	/**
	 * Sets the total billed premium of this cmic account entry.
	 *
	 * @param totalBilledPremium the total billed premium of this cmic account entry
	 */
	public void setTotalBilledPremium(String totalBilledPremium);

}